<a href="https://colab.research.google.com/github/fidis1993/Machine-Learning/blob/main/00_tensorflow_begin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Notebook 00
 In these notebooks, we will see the basics of tensorflow. Ultimately, the goal is to understand the basics and then procceed to writing DL models. First things first, the basics!

##Contents:
- Learn about tensors.
- Process information/data in tensor form.
- Manipulating the info/data.
- Tensors and NumPy.

In [1]:
#Import TensorFlow
import tensorflow as tf

#Its good practice to check our version of the library. Make sure nothing is amiss.
print(tf.__version__)

2.12.0


In [2]:
#Creating a new tensor with tf.constant()

#plain number, 0 dimensions
scalar_num = tf.constant(7)
#using the .numpy() method in order to print it as an numpy array
print(scalar_num.numpy())

#1-dim
d1 = tf.constant ([1],shape=[1,])
print("1 Dimension  \n",d1.numpy())
#2-dim
d2 = tf.constant([2],shape=[2,2])
print("\n2 Dimensions  \n",d2.numpy())
#3-dim
d3 = tf.constant([3],shape=[2,3,2])
print("\n3 Dimensions  \n",d3.numpy())

7
1 Dimension  
 [1]

2 Dimensions  
 [[2 2]
 [2 2]]

3 Dimensions  
 [[[3 3]
  [3 3]
  [3 3]]

 [[3 3]
  [3 3]
  [3 3]]]


In [3]:
#A way of finding the dimensions of an element, we can use the method .ndim
d3.ndim

3

In [4]:
#All tensors created are constants, meaning are unchangable. In order for them to not be that way we would use the .Variable() method.
d2_tensor = tf.Variable([[2,2,2],[2,2,2]])
d2_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2]], dtype=int32)>

In [5]:
#Creating tensors containing random numbers with random.uniform() and not random.Generator.from_seed().
#Key difference is their assigned values and with a seed we can reproduce the outputs of the tensor while uniform() are completely random.
#In case we want to test in the future, a model with reaccuring tensors info.
random_tens = tf.random.uniform(shape=(5,5),maxval = 255,dtype =tf.int32 )
random_tens


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[133, 237, 220, 120,  91],
       [ 21,  28, 248, 223, 233],
       [ 16,  80, 146, 213,  92],
       [230,  19,  56,  46, 135],
       [  7, 232,  70, 247, 241]], dtype=int32)>

In [6]:
# explore the random.shuffle() method. It is used for mixing the contents of a tensor based on its 1st dimension.
print("Our starting tensor: \n",random_tens.numpy())
random_tens = tf.random.shuffle(random_tens)
print("Our tensor after shuffling: \n",random_tens.numpy())

Our starting tensor: 
 [[133 237 220 120  91]
 [ 21  28 248 223 233]
 [ 16  80 146 213  92]
 [230  19  56  46 135]
 [  7 232  70 247 241]]
Our tensor after shuffling: 
 [[ 21  28 248 223 233]
 [133 237 220 120  91]
 [ 16  80 146 213  92]
 [230  19  56  46 135]
 [  7 232  70 247 241]]


### Operation with tensors
- Multiplication
- Addition


In [8]:
#Addition using the default operation
random_tens2 = tf.random.uniform(shape=(5,5),maxval = 255, dtype = tf.int32)
resulting_tens1 = random_tens + random_tens2
resulting_tens1

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 38, 107, 430, 350, 445],
       [275, 292, 439, 121, 201],
       [ 36, 201, 281, 433, 312],
       [274,  58, 276, 267, 236],
       [230, 328, 230, 329, 432]], dtype=int32)>

In [11]:
#Addition wih addition method
resulting_tens2 = tf.math.add(random_tens,random_tens2)
resulting_tens2

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 38, 107, 430, 350, 445],
       [275, 292, 439, 121, 201],
       [ 36, 201, 281, 433, 312],
       [274,  58, 276, 267, 236],
       [230, 328, 230, 329, 432]], dtype=int32)>

In [12]:
#Likewise for multiplication
resulting_tens3 = tf.matmul(random_tens,random_tens2)
resulting_tens3

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 71064,  64272, 129774, 125644, 129118],
       [ 65888,  63578, 146769,  99510, 132167],
       [ 44440,  40469, 101722,  88849,  83397],
       [ 39857,  40745,  85301,  62785,  93601],
       [ 99074,  54552, 154432,  90870, 113382]], dtype=int32)>