<a href="https://colab.research.google.com/github/fidis1993/Machine-Learning/blob/main/01_tensorflow_begin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Notebook 01
 In these notebooks, we will see the basics of tensorflow. Ultimately, the goal is to understand the basics and then procceed to writing DL models. First things first, the basics!

##Contents:
- Learn about tensors.
- Process information/data in tensor form.
- Manipulating the info/data.
- Tensors and NumPy.

In this notebook I will focus on more tensor manipulation.
I will play around with finding values that are usually of interest when working with ML models. Such as maximum value, minimum, mean and sum.


In [1]:
#Import TensorFlow
import tensorflow as tf

#Its good practice to check our version of the library. Make sure nothing is amiss.
print(tf.__version__)

2.12.0


In [6]:
#Create a random tensor with a control range of parameters and type. We need to be familiar with those properties.
ranTensor = tf.random.uniform(shape =(10,10),maxval = 255, dtype =tf.float16 )
ranTensor

array([[233.6  , 133.5  , 118.8  , 138.5  , 199.2  ,  60.25 , 111.3  ,
         12.95 , 207.6  , 129.2  ],
       [ 32.12 , 248.8  ,  15.69 , 160.1  , 204.   ,  95.4  , 237.4  ,
        175.5  , 202.8  , 116.56 ],
       [107.8  ,  10.46 , 146.9  , 136.8  , 144.9  , 216.4  , 205.5  ,
        200.2  ,  48.8  , 106.3  ],
       [187.5  , 190.5  ,   2.738,  86.44 ,  71.   , 219.9  ,  34.12 ,
        204.5  , 209.1  , 119.5  ],
       [ 58.03 ,  31.88 , 133.   ,  98.1  ,  50.56 , 172.6  ,  84.94 ,
         59.75 , 196.5  , 113.56 ],
       [172.6  , 142.5  , 231.6  ,  65.5  ,  84.2  , 215.9  ,  10.95 ,
        221.6  ,  70.   , 223.1  ],
       [227.1  , 227.1  , 146.4  , 177.5  ,  87.44 ,  78.94 ,  72.2  ,
         25.16 , 122.   , 175.8  ],
       [114.3  , 135.5  ,  11.7  ,   3.734, 228.9  , 244.8  , 243.8  ,
         74.94 ,  76.44 , 148.9  ],
       [243.2  , 116.56 ,  70.5  ,  33.12 , 245.8  , 151.4  , 113.56 ,
        208.4  ,  94.6  ,  30.88 ],
       [242.   , 137.   , 212.6  , 23

In [8]:
#Finding max using reduce_max() method
max = tf.reduce_max(ranTensor)
max

<tf.Tensor: shape=(), dtype=float16, numpy=248.8>

In [9]:
#Likewise for min using reduce_min()
min = tf.reduce_min(ranTensor)
min

<tf.Tensor: shape=(), dtype=float16, numpy=2.738>

In [10]:
# for mean we will use reduce_mean()
mean = tf.reduce_min(ranTensor)
mean

<tf.Tensor: shape=(), dtype=float16, numpy=2.738>

In [11]:
# for sum we will use reduce_sum()
sum = tf.reduce_sum(ranTensor)
sum

<tf.Tensor: shape=(), dtype=float16, numpy=13144.0>

In [15]:
#Finding the standard deviation
std = tf.math.reduce_std(tf.cast(ranTensor,dtype = tf.float32))
std

<tf.Tensor: shape=(), dtype=float32, numpy=73.82891>

In [18]:
#For finding variance, we will need to import the probability library
# side comment: It wasn't necessary.
import tensorflow_probability as tfp
#Also lets cast our tensor into ints 32bit for clearer results.
var = tfp.stats.variance(tf.cast(ranTensor,dtype = tf.int32))
var

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([5599, 5108, 6029, 4484, 5512, 4725, 5924, 7326, 4667, 2674],
      dtype=int32)>

In [20]:
#this finds the max value in axis, default is 0.For more precission we can specify the axis we want to find the max or
pos_array =tf.argmax(ranTensor)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([8, 1, 5, 9, 8, 7, 7, 5, 3, 5])>

In [23]:
#Change axis to 1.Where 1 should  be the rows and 0 columns in this example.
pos_axis0 =tf.argmax(ranTensor,1)
pos_axis0

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 5, 5, 8, 2, 0, 5, 4, 0])>